version: "3.9"

x-common-config: &COMMON_CONFIG
  networks:
    - sunlight-app-network
  restart: unless-stopped

services:
  frontend:
    <<: *COMMON_CONFIG
    container_name: sunlight-fe
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:${FRONTEND_PORT:-3009}/api
    image: govolt-sunlight/fe
    ports:
      - ${FRONTEND_PORT:-3009}:80
  backend:
    <<: *COMMON_CONFIG
    container_name: sunlight-be
    build:
      context: ./backend
    image: govolt-sunlight/be
    environment:
      - PORT=8000
    ports:
      - ${PORT-8000}:8000

networks:
  sunlight-app-network:
